site_name: Mi Documentación

theme:
  name: material
  features:
    - navigation.tabs


nav:
  - Inicio: index.md
  - Python:
      - Introducción: python/index.md
  - JavaScript:
      - 01. Introducción (T1): javascript/T1_introduccion.md
      - 02. Funciones (T2): javascript/T2_funciones.md
      - 03. Arrays (T3): javascript/T3_arrays.md
      - 04. DOM (T4): javascript/T4_DOM.md
      - 05. Eventos (T5): javascript/T5_eventos.md
      - 06. Formularios (T6): javascript/T6_formularios.md
  - PHP:
      - Introducción: php/index.md
  - SQL:
      - Introducción: sql/index.md

plugins:
  - search:
      lang: 
        - es
        - en
      separator: '[\s\-]+'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
