site_name: Mi Documentación

theme:
  name: material

nav:
  - Inicio: index.md
  - Python:
      - Introducción: python/index.md
  - JavaScript:
      - Introducción: javascript/index.md
  - PHP:
      - Introducción: php/index.md
  - SQL:
      - Introducción: sql/index.md

